[package]
name = "keyboard-windows-tip"
version = "0.1.0"
edition = "2024"
description = "the Windows text input processor for asciimath-unicode"
repository = "https://github.com/hafacc/asciimath-unicode"
license = "MIT"
publish = false

[lib]
name = "asciimath_unicode_tip"
crate-type = ["cdylib", "rlib"]

[build-dependencies]
keyboard-windows-resource = { path = "../resource" }

[dependencies]
keyboard-core = { path = "../../keyboard-core" }

[target.'cfg(windows)'.dependencies]
windows-core = "0.62.2"
windows-registry = "0.6.1"

[target.'cfg(windows)'.dependencies.windows]
version = "0.62.2"
features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_Ole",
    "Win32_System_SystemServices",
    "Win32_System_Variant",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_TextServices",
    "Win32_UI_WindowsAndMessaging",
]
