[package]
name = "keyboard-windows-app"
version = "0.1.0"
edition = "2024"
description = "the Windows companion program for the asciimath-unicode keyboard"
repository = "https://github.com/hafacc/asciimath-unicode"
license = "MIT"
publish = false

[[bin]]
name = "AsciiMathUnicode"
path = "src/main.rs"

[build-dependencies]
keyboard-windows-resource = { path = "../resource" }

[dependencies]
keyboard-windows-tip = { path = "../tip" }
