# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tests
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - run: cargo install wasm-pack
    - run: bun install
    - run: bun export:wasm
    - run: bun lint
    - run: bun test
    - run: bun export:bundle
    - run: bun export:next
